# Bu dosya, Python betiğinin ayarlarını içerir.
# Sunucu adresi değiştiğinde sadece 'base_url' kısmını güncelleyin ve
# değişiklikleri GitHub'a gönderin (push). Action otomatik olarak çalışacaktır.

# Her kanal URL'sinin başına eklenecek olan ve sürekli değişen ana sunucu adresi.
base_url: "http://cb286df8.rossteleccom.net/iptv/ZCWPCL9K3LR827/"

# Kanalların çekileceği kaynak M3U listesinin tam adresi.
source_playlist_url: "http://972597723f0a.mylistbest.com/playlists/uplist/8c4d4375456732c85eab29f8b8caf818/playlist.m3u8"

# Oluşturulacak yeni M3U dosyasının adı.
output_file: "donusturulmus_liste.m3u8"
