
# .github/workflows/update_m3u.yml
# Bu GitHub Actions workflow'u, M3U listesini periyodik olarak günceller.

name: rec Listesini Otomatik Güncelle

on:
  # Bu workflow'u Actions sekmesinden manuel olarak çalıştırmanıza olanak tanır
  workflow_dispatch:
  
  # Belirlenen zaman aralığında otomatik çalışır (cron job)
  # Bu örnek 6 saatte bir çalışacak şekilde ayarlanmıştır
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-playlist:
    # İşlemin çalışacağı sanal makineyi belirtir
    runs-on: ubuntu-latest

    # YENİ EKLENEN KISIM: İş akışına repoya yazma izni verir
    # Bu, 'git-auto-commit-action' adımının çalışabilmesi için gereklidir.
    permissions:
      contents: write

    steps:
      # Adım 1: Repoyu sanal makineye klonlar
      # Bu sayede betiğimize ve diğer dosyalara erişebiliriz
      - name: Depoyu Klonla (Checkout)
        uses: actions/checkout@v4

      # Adım 2: Python ortamını kurar
      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Kullanılacak Python sürümü

      # Adım 3: Gerekli Python kütüphanelerini yükler
      # Betiğimizin çalışması için 'requests' kütüphanesi gerekiyor
      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Adım 4: M3U işleme betiğini çalıştırır
      - name: M3U Dosyasını İşle
        run: python process_m3u.py

      # Adım 5: Eğer dosyada değişiklik varsa, değişiklikleri repoya commit'ler ve push'lar
      # Bu sayede güncellenmiş liste reponuzda her zaman hazır olur
      - name: Değişiklikleri Commit'le ve Push'la
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Commit mesajı
          commit_message: "chore: İşlenmiş M3U listesi otomatik güncellendi"
          # Sadece bu dosyadaki değişiklikleri dikkate al
          file_pattern: "recfilm_processed.m3u"
          # Commit'i yapacak olan kullanıcı bilgileri
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"