# daily_dlhd_update.yml
name: Daily DaddyLive M3U Update

on:
  schedule:
    # Her gün saat 08:00'de çalışır
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv python-dateutil

      - name: Run DaddyLive Script
        run: |
          python dlhd_auto.py

      - name: Upload generated M3U
        uses: actions/upload-artifact@v3
        with:
          name: dlhd_m3u
          path: dlhd.m3u