# Bu GitHub Actions iş akışının adı
name: M3U Çalma Listesini Güncelle

# Bu iş akışının ne zaman çalışacağını belirleyen tetikleyiciler
on:
  # Her 6 saatte bir otomatik olarak çalıştırır
  schedule:
    - cron: '0 */6 * * *'
  
  # GitHub Actions arayüzünden manuel olarak çalıştırmaya izin verir
  workflow_dispatch:

jobs:
  update_playlist:
    # İşin çalışacağı sanal makine ortamı
    runs-on: ubuntu-latest
    
    # Bu işin repository'ye yazma izni olması için gereklidir
    permissions:
      contents: write

    steps:
      # 1. Adım: Repository'deki kodları sanal makineye kopyalar
      - name: Depoyu Klonla (Checkout)
        uses: actions/checkout@v4

      # 2. Adım: Python 3.x ortamını kurar
      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Adım: Python betiğinin ihtiyaç duyduğu 'requests' kütüphanesini yükler
      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Adım: M3U listesini işleyen Python betiğini çalıştırır
      - name: M3U İşleyici Betiği Çalıştır
        run: python m3u_processor.py

      # 5. Adım: Oluşturulan yeni listeyi repository'ye commit'ler ve push'lar
      - name: Değişiklikleri Commit'le ve Push'la
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${{ env.OUTPUT_FILENAME }}
          # Dosyada değişiklik varsa commit at, yoksa bir sonraki adıma geç
          git commit -m "Otomatik M3U çalma listesi güncellemesi" || exit 0
          git push
        env:
          # Python betiğindeki çıktı dosyası adını burada da kullanıyoruz
          OUTPUT_FILENAME: tr_list.m3u